name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Adjust if you have a different build command

      - name: Run tests
        run: npm test  # Adjust according to your testing command

      - name: Upload Test Results
        if: success()  # This step runs if the previous steps were successful
        uses: actions/upload-artifact@v2
        with
